title: "御作法Book"
summary: "kintoneカスタマイズをする際の、押さえておきたい御作法・コーディングルール。"
topics: ["kintone", "コーディングルール"] # トピック（5つまで）
published: true # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - 1-1_imoni-manner-book #チャプター1
  - 1-2_imoni-manner-book
  - 2-1_imoni-manner-book
  - 2-2_imoni-manner-book
  - 2-3_imoni-manner-book
  # - 2-4_imoni-manner-book
  - 3-1_imoni-manner-book
  - 3-2_imoni-manner-book
  - 3-3_imoni-manner-book
  - 3-4_imoni-manner-book
  - 3-5_imoni-manner-book
  # - 3-6_imoni-manner-book
  # - 4-1_imoni-manner-book
